### ISSUE TITLE
question regarding concurrency

### ISSUE THREAD

**Issue by apmcodes** [distributedio/titan#227]
We are designing a message/ task queue based on Titan/ TiKV and have concurrency related query.

USE CASE: single queue with millions of messages consumed by multiple (10) consumers
Queue is implemented using 2 sorted sets (1 for unack/ active messages), hash (storing message payload)
1) Will this create contention (many transactions rfailure/ retry) on TiKV as multiple consumers accessing these 3 keys (2 sorted set, 1 hash)?
2) Will sharding (partitions) the queue (into multiple queues) and each shard is consumed by a single consumer will achive better output and lower contention?

Need help to understand how concurrent client requests are handled by Titan and passed to TiKV. Does Titan pass the client requests concurrently/ sequentially to TiKV?

**Comment by arthurkiller** [comment]
@apmcodes

TiKV process transaction via 2PC which is inspired by `percolator`
Under this transaction module, every transaction has a `primary key` called __PK__, and the conflict occurs on the parallel access on the same __PK__.

As for your question 1, if your queue access module was based on topic, and each topic relay on __an independent sorted set__, the transaction ___commit-conflict-retry___ will occurs frequently.

Question 2 is about how the data structure is organized. To be simplicity most of the titan data structures have 2 type of keys: 
* `metakey` for data struct meta info, with a uniform prefix.
* `datakeys` represent a set of data keys that is associated with the same data key prefix.

TiKV will do the sharding on the whole keyspace.

And we are taking into consideration about implementing the `Stream` data structure on __redis v6__.

> https://redis.io/topics/streams-intro

`Stream` can be used as a reliable message dispatcher which provides the `product` and `consuming` primitive.

**Comment by arthurkiller** [comment]
CC @shafreeck @nioshield

**Comment by shafreeck** [comment]
Hi @apmcodes, Thanks for choosing Titan.

@arthurkiller  gave the design details of the transaction about Titan. Directly to your question:

1. Yes, it will create contention if it has a concurrent write(but I think it should not have concurrent write in your case). This is caused by the sorted set, when adding a member, the sorted set's meta key will be updated. The `hash` does not cause contention because we avoid updating its meta when doing `hset`.
2. Yes, sharding really helps, but you still need to do a benchmark first to get more confidence.

I don't know your design of the `ack/unack` queue, is the queue shared by multiple consumers? In my experience, the `ack/unack` queue should belong to a single consumer, in which case, there is no contention at all.

Or maybe your queue supports the concept consumer group, and the consumers inside the group share the same `ack/unack`, this will cause contention if you the high frequency of acks.

**Comment by nilbounce** [comment]
Thank you @arthurkiller @shafreeck for the above inputs, will keep it in mind while designing the message queue. Will post further if encounter any queries.

**Comment by arthurkiller** [comment]
> Thank you @arthurkiller @shafreeck for the above inputs, will keep it in mind while designing the message queue. Will post further if encounter any queries.

with pleasure, and if you have any problems while trying `titan` please feel free to let us know.
